# Generated by groundwork — do not edit manually.
# Resource type: aws_sqs_queue

include "root" {
  path = find_in_parent_folders()
}

inputs = {
  # TODO: fill in required inputs for aws_sqs_queue
}