# Generated by groundwork — do not edit manually.

remote_state {
  backend = "s3"

  config = {
    bucket         = "python-api-tf-state"
    key            = "${path_relative_to_include()}/terraform.tfstate"
    region         = "us-east-1"
    encrypt        = true
    dynamodb_table = "python-api-tf-state-lock"
  }

  generate = {
    path      = "backend.tf"
    if_exists = "overwrite_terragrunt"
  }
}
