# Generated by groundwork — do not edit manually.
# Resource type: aws_s3_bucket

include "root" {
  path = find_in_parent_folders()
}

inputs = {
  # TODO: fill in required inputs for aws_s3_bucket
}