# Generated by groundwork — do not edit manually.
# Resource type: aws_dynamodb_table

include "root" {
  path = find_in_parent_folders()
}

terraform {
  source = "tfr:///terraform-aws-modules/dynamodb/aws///"
}

inputs = {
  # TODO: fill in required inputs for aws_dynamodb_table
}