# Generated by groundwork — do not edit manually.

terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }
}

resource "aws_sqs_queue" "main" {
  name                      = var.queue_name
  message_retention_seconds = var.message_retention_seconds
  tags                      = var.tags
}

variable "queue_name" {
  description = "Name of the SQS queue"
  type        = string
}

variable "message_retention_seconds" {
  description = "Number of seconds SQS retains a message"
  type        = number
  default     = 345600
}

variable "tags" {
  description = "Tags to apply to resources"
  type        = map(string)
  default     = {}
}

output "queue_url" {
  description = "URL of the SQS queue"
  value       = aws_sqs_queue.main.url
}

output "queue_arn" {
  description = "ARN of the SQS queue"
  value       = aws_sqs_queue.main.arn
}
